backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\SignupForm;
use common\models\UserProfile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'signup', 'error', 'confirm-signup'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['their'],
                    ],

                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if (Yii::$app->user->can('their')) {
                return $this->goBack();
            } else {
                Yii::$app->user->logout();
                return $this->render('login', [
                    'model' => $model,
                ]);
            }

        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm(['scenario' => SignupForm::SCENARIO_COMPANY]);
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                   return $this->redirect('/site/confirm-signup');
                    //return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionConfirmSignup()
    {
        return $this->render('confirm-signup');
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use modules\flight\frontend\models\Tokens;
use backend\models\Corp;
use backend\modules\integra\models\base\CorpModules;
use console\models\FlightBookStatus;
use modules\organisation\models\flights\base\TBook;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\UserProfile;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

use backend\modules\integra\models\base\CorpModuleAssignment;

use backend\modules\integra\services\IntegraService;
use modules\flight\frontend\models\base\Flights;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $session = Yii::$app->session;
        $session->remove('tokenID');
        $session->remove('flightID');
        return $this->render('index');
    }

    public function actionTest()
    {
//        $tokens = Tokens::findAll(['pult_name' => 'qway']);
//        $count = 0;
//
//        if ($tokens) {
//            foreach ($tokens as $token) {
//                Tokens::isSessionAlive($token);
//                $count++;
//            }
//        }
//
//        return $count;
        FlightBookStatus::runRobot();
    }

    public function actionRailWays()
    {
        return $this->render('rail');
    }

    public function actionHotels()
    {
        return 'В разработке';
    }

    public function actionNextTrip()
    {
        return $this->render('next-trip');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if (UserProfile::findOne(['user_id' => Yii::$app->user->identity->id]) == null) {
                return $this->redirect(['/profile/user-profile/create']);
            }
//            return $this->redirect(['/profile/user-profile/create']);
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


    public function actionProfile()
    {
        return $this->render('profile');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm(['scenario' => SignupForm::SCENARIO_USER]);
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    if (UserProfile::findOne(['user_id' => Yii::$app->user->identity->id]) == null) {
                        return $this->redirect(['/profile/user-profile/create']);
                    }
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionOffer()
    {
        return $this->render('offer');
    }

    public function actionPaymentMethods()
    {
        return $this->render('payment-methods');
    }
}

frontend/views/site/_offer-content.php
<h1>Публичная оферта Qway.kz</h1>

<p>ТОО «Qway», расположенное по адресу: Республика Казахстан, г. Алматы, ул. Сатпаева, 30А/3 именуемое в дальнейшем «Агент», предлагает любому физическому лицу, индивидуальному предпринимателю или юридическому лицу, в дальнейшем именуемому «Клиент», платные услуги, службы и сервисы в сети Интернет, а также программное обеспечение и иные программные продукты (далее – Услуги и/или Продукты).</p>
<p>Настоящее предложение в соответствии со ст. 395 Гражданского Кодекса РК является публичной офертой (далее – Договор), полным и безоговорочным принятием (акцептом) условий которой в соответствии со ст. 396 Гражданского кодекса РК считается осуществление Клиентом конклюдентных действий – осуществление поиска, бронирования и покупки Билетов в системе Агента, расположенной на Сайте Агента.</p>

<h3>1. ТЕРМИНЫ И ОПРЕДЕЛЕНИЯ.</h3>
<ul>
    <li>1.1. Сайт Агента – WEB-сайт, расположенный по адресу http://www.Qway.kz,  в сети Интернет. На Cайте Агента Клиентам круглосуточно и бесплатно предоставляется в том числе информация, необходимая для заключения и исполнения настоящего Договора, публикуются все официальные документы Агента и т. д.;</li>
    <li>1.2. ГДС (GDS) — глобальные системы дистрибуции авиабилетов, используемые большинством авиакомпаний.</li>
    <li>1.3. Бронь — предварительный резерв авиабилетов конкретной авиакомпании по конкретному направлению на конкретные даты, закрепляемый за Клиентом по определенной стоимости.</li>
    <li>1.4. Билет — (пассажирский билет и багажная квитанция) — документ на перевозку, выдаваемый авиакомпанией либо его агентами, удостоверяющий заключение договора с условиями воздушной перевозки пассажира.</li>
    <li>1.5. Лоукостеры, авиадискаунтеры — низкобюджетные авиаперевозчики, стоимость авиабилетов на которые может быть в несколько раз ниже билетов традиционных авиалиний. Как правило, подобная стоимость достигается отсутствием бесплатного питания на борту, отсутствием бесплатного багажа, а также рядом других ограничений, которые публикуются на сайте авиаперевозчика. Подобные авиаперевозчики выделены на Сайте Агента в отдельный раздел, либо в случае размещения в общем разделе поиска авиабилетов имеют специальную пометку «лоукостер».</li>
</ul>

<h3>2. ПРАВА И ОБЯЗАННОСТИ КЛИЕНТА</h3>
<ul>
    <li>2.1. Клиент несет ответственность за правильность введенных данных, в том числе за соответствие введенных данных о пассажирах их паспортным данным. При любых изменениях личных данных пассажиров, по международным стандартам, необходимо переоформление билетов по тарифам, доступным на момент переоформления.</li>
    <li>2.2. Билеты считаются купленными Клиентом по факту отправки Агентом письма с Билетом (маршрутной квитанцией) на электронную почту Клиента, указанную при бронировании.</li>
    <li>2.3. Покупая (оплачивая) билеты на сайте Qway.kz, Клиент подтверждает, что самостоятельно изучил, понял и принимает Правила применения тарифа к билету, отправляемые на указанный Клиентом электронный адрес на английском языке и/или подтверждает, что Агент проинформировал его (Клиента) в Публичной оферте о праве получить разъяснение Правил применения тарифа на казахском и/или русском языке до покупки (оплаты) билета, обратившись в службу поддержки, отправив запрос на электронную почту, и/или по телефонам, указанным в разделе «Контакты». Клиент соглашается, что самостоятельно решает обращаться или не обращаться в службу поддержки за разъяснением Правил применения тарифа на казахском и/или русском языке и принимает, что после оплаты билета, все процедуры, связанные с обменом, возвратом билета производятся Агентом только в строгом соответствии с Правилами применения тарифа и Клиент не имеет претензий по содержанию данных Правил применения тарифа, так как подтвердил своё согласие с ними.</li>
    <li>2.4. Клиенту необходимо самостоятельно уточнять информацию о допустимом весе, габаритах и количестве единиц багажа, ручной клади, при этом вся устная информация, получаемая от Агента, носит лишь рекомендательный характер и актуальна на день информирования. </li>
    <li>2.5. Клиенту необходимо самостоятельно уточнять информацию, по какому документу необходимо лететь (внутренний документ или международный паспорт), о необходимых визах, разрешениях на въезд, прививках, страховых полисах и иных разрешительных документах и процедурах для страны пункта назначения или пересадочного пункта, при этом вся устная информация, получаемая от Агента, носит лишь рекомендательный характер и актуальна на день информирования.</li>
    <li>2.6. При оплате наличными в офисах партнёров Агента, сотрудники данных офисов не обязаны консультировать Клиента по каким-либо вопросам, так как осуществляют только приём оплаты за билеты Агента и не являются сотрудниками Агента, всю необходимую информацию Клиент вправе получить в службе поддержки Агента, связавшись любым удобным способом, указанным в разделе «Контакты».</li>
</ul>

<h3>3. ПРАВА И ОБЯЗАННОСТИ АГЕНТА</h3>
<ul>
    <li>3.1. При оплате Клиентом авиабилетов банковской картой, Агент имеет право запросить у Клиента скан или фотографию лицевой стороны банковской карты, где будут четко различимы первые 6 и последние 4 цифры номера карты, а также копию документа, удостоверяющего личность. В случае отказа Клиента, Агент имеет право отказать в предоставлении услуг, а также аннулировать ранее купленные Клиентом авиабилеты.</li>
    <li>3.2. Агент имеет право отправлять Клиенту информационные сообщения по электронной почте и/или посредством СМС, связанные с авиаперелетами, такие как информация о ценах, об изменениях в брони, изменениях и отменах рейсов и др.</li>
    <li>3.3. Предоставляемая Клиентом персональная информация (имя, адрес, телефон, e-mail, номер кредитной карты) является конфиденциальной и не подлежит разглашению третьим лицам, за исключением случаев, предусмотренных Законодательством РК.</li>
    <li>3.4. Информация о ценах, публикуемая на сайте и в мобильных приложениях до момента предварительного бронирования, а также в информационных письмах-рассылках, не является офертой. Ввиду ограниченного количества билетов по каждому тарифу, установленному авиакомпанией, актуальная цена появляется после ввода паспортных данных и появления информации о том, что билеты успешно забронированы.</li>
</ul>

<h3>4. УСЛОВИЯ ОБМЕНА И ВОЗВРАТА АВИАБИЛЕТОВ</h3>
<ul>
    <li>4.1. Обмен и возврат авиабилетов осуществляется ежедневно 24 часа в сутки <strong>в соответствии с правилами применения тарифов</strong>, устанавливаемыми авиакомпанией (Далее — «Правила применения тарифов»), которые прикрепляются к письму, отправляемому после создания Брони на электронную почту Клиента, указанную в момент бронирования. Для заявки на возврат или обмен необходимо написать запрос на help@qway.kz с того Email адреса, который указывался при бронировании или позвонить с того номера телефона, который указывался при бронировании.</li>
    <li>4.2. При отмене авиабилетов возврат денежных средств производится строго в соответствии с Правилами применения тарифов.</li>
    <li>4.2.1 Рассчитанная к возврату сумма с учётом возможных штрафов авиакомпании, согласно внутреннему регламенту платежных систем Visa/MasterCard, перечисляется на счёт карты, по которой ранее была совершена покупка, от двух до тридцати рабочих дней (зависит от банка, выпустившего карту) с момента запуска процесса отмены/возврата.</li>
    <li>4.2.2 Если вы оплачивали забронированные на Qway авиабилеты в офисе компании, то в первую очередь необходимо отправить нам заявку на возврат/обмен. Только после обработки вашей заявки мы отправляем уведомление , где была произведена оплата, после чего можно получить сумму, подлежащую к возврату.</li>
    <li>4.3. Услуга обмена билета является платной. При обмене билета на рейсы внутри Республики Казахстан стоимость обмена составляет 1500 (Одна тысяча пятьсот) тенге, при обмене билета на международный рейс стоимость обмена билета в эконом классе составляет 4000 (Четыре тысячи) тенге, в бизнес классе - 6000 (Шесть тысяч) тенге.</li>
    <li>4.4 Услуга возврата авиабилета является платной. При возврате билета на рейсы внутри Республики Казахстан стоимость возврата составляет 2500 (Две тысячи пятьсот) тенге, при возврате билета на международный рейс стоимость возврата билета в эконом классе составляет 4000 (Четыре тысячи) тенге, в бизнес классе - 6000 (Шесть тысяч) тенге.</li>
    <li>4.5 При вынужденном возврате услуга возврата осуществляется бесплатно.</li>
    <li>4.6 Для оформления возврата авиабилета пассажир предъявляет билет с полетным купоном. Билет с использованными полетными купонами недействителен для перевозки пассажира и возврата денег. Авиакомпания принимает полетные купоны для перевозки пассажира и его багажа только в строгой последовательности, начиная с пункта отправления, указанного в пассажирском купоне.</li>
    <li>4.7. Авиабилеты на перелеты лоукостерами обмену и возврату не подлежат.</li>
</ul>

<h3>5. ОТВЕТСТВЕННОСТЬ СТОРОН</h3>
<ul>
    <li>5.1. Результаты поиска цен на билеты по выбранному Клиентом направлению, отображаемые на Сайте Агента, не являются окончательными, а окончательные цены на билеты указываются только в момент появления страницы для заполнения данных по брони и действительны на момент появления, при этом в момент нажатия на кнопку «Забронировать» происходит фиксация стоимости Билета в ГДС при наличии достаточного количества мест в ГДС.</li>
    <li>5.2. Бронь, создаваемая более чем на 30 минут, до момента оплаты и выписки билета может быть изменена или отменена авиакомпанией в одностороннем порядке с уведомлением Агента посредством ГДС, вследствие чего Агент не несет ответственности за изменение стоимости забронированных авиабилетов, при этом Агент обязуется приложить все усилия для уведомления Клиента о соответствующих изменениях путем оповещения Клиента на электронную почту или мобильный телефон, указанные Клиентом в момент создания Брони.</li>
    <li>5.3. В случае создания Клиентом двух или более броней на одних и тех же пассажиров на один и тот же рейс, авиакомпании в одностороннем порядке могут аннулировать дублирующиеся брони с более дешевой стоимостью.</li>
</ul>

<h3>6. Прочие условия</h3>
<ul>
    <li>Пользователь согласен с тем, что совершая покупки на сайте Qway.kz, он передает свои личные данные и на его электронный адрес могут направляться письма и сообщения, в том числе рекламного характера.</li>
    <li>6.1. Пользователь согласен с тем, что Qway.kz использует и обрабатывает персональные данные Пользователя.</li>
    <li>6.2. Qway.kz использует информацию в том числе:
        <ul><li>- для выполнения своих обязательств перед Пользователем;</li></ul>
    </li>
    <li>6.3. Qway.kz обязуется не разглашать полученную от Пользователя информацию. Не считается нарушением предоставление Qway.kz информации агентам и третьим лицам, действующим на основании договора с Qway.kz, для исполнения обязательств перед Пользователем. Не считается нарушением обязательств разглашение информации в соответствии с обоснованными и применимыми требованиями закона. Qway.kz вправе использовать технологию «cookies». «Cookies» не содержат конфиденциальную информацию и не передаются третьим лицам. Qway.kz получает информацию об ip-адресе посетителя Сайта. Данная информация не используется для установления личности Пользователя, за исключением случаев мошеннических действий Пользователя.</li>
    <li>6.4. Пользователь несет ответственность за достоверность передаваемых Qway.kz персональных данных.</li>
</ul>

<h3>7. Информационные сообщения</h3>
<ul>
    <li>Пользователь дает свое согласие на получение обновленной информации о деятельности компании Qway.kz, информационных сообщений с рекламными и акционными предложениями и объявлениями о продаже, а также информации о новостях и предложениях партнеров Qway.kz посредством электронной почты.</li>
</ul>

<p>8. Пользователь дает согласие на запись телефонных разговоров для повышения качества обслуживания и подтверждения устных заявлений Пользователя, сохранение паспортных данных пассажиров исключительно в целях удобства последующих покупок.</p>
<p>9. Пользователь уведомлен и соглашается, что при использовании мобильного приложения Qway.kz передается следующая информация: тип операционной системы мобильного устройства Клиента, версия и идентификатор приложения, состояние сети, статистику использования приложения и другую техническую информацию.</p>

frontend/views/site/_payment-logo-block.php
<div class="payment-logo">
    <!--<span><img src="/images/payment-logo.png" alt=""></span>-->
    <div class="item"><img style="width: 90px;" src="/images/footer/visa.png" alt=""></div>
    <div class="item"><img style="width: 90px;" src="/images/footer/mastercard.png" alt=""></div>
    <span><?= \yii\helpers\Html::a('Договор публичной оферты', \yii\helpers\Url::toRoute('/site/offer')) ?></span>
    <!--<i class="fa fa-cc-visa" aria-hidden="true"></i>
    <i class="fa fa-cc-mastercard" aria-hidden="true"></i>-->
    <!--<img src="/images/footer/visa.png" alt="">
    <img src="/images/footer/mastercard.png" alt="">-->

</div>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О компании';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about qway-wrap">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Qway- онлайн-сервис для покупки авиабилетов и бронирования отелей по всему миру.</p>

    <h1>Контакты</h1>
    <p>
        ТОО «Qway»<br>
        г. Алматы, ул. Сатпаева, дом 30/А/3<br>
        тел: 8(727) 346 83 86<br>
        E-mail: info@qway.kz<br>
    </p>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use \modules\flight\frontend\models\base\FlightElectronicTickets;
/* @var $this yii\web\View */

$this->title = 'Главная';
$session = $session = Yii::$app->session;
$ticketData = [];
$ticketRouteStr = '';
//$session->destroy();
//$session->remove('exchangeTicketId');
//$session->remove('exchangeTicketNumber');
if ($session->has('exchangeTicketId')) {
    $ticket = FlightElectronicTickets::find()->where(['id' => $session->get('exchangeTicketId')])->with('itineraries')->one();
    foreach ($ticket->itineraries as $key => $segment) {
        $ticketRouteStr .= $segment->from . '(' . $segment->cityFrom->name_ru . ')-' . $segment->to . '(' . $segment->cityTo->name_ru . ')';
        if ($key < count($ticket->itineraries)-1) {
            $ticketRouteStr .= ', ';
        }
    }
} else {
    $session->remove('exchangeTicketId');
    $session->remove('exchangeTicketNumber');
}

?>
<div class="site-index">
    <?php if ($session->has('exchangeTicketId')) :?>
        <div class="exchange-data">
            <h1 class="exchange-data-title">Билет на обмен: <?=$session->get('exchangeTicketNumber');?> <?=$ticketRouteStr;?> <button class="cancel-exchange btn btn-default" onclick="cancelToExchange();">Отменить</button></h1>
        </div>
        <div id="search-form-flight-wrap">
            <?= $this->render('@modules/flight/frontend/views/flight/_search-form-flight', ['ticketData' => $ticketData]); ?>
        </div>
    <?php else :?>
        <div id="search-form-flight-wrap">
            <?= $this->render('@modules/flight/frontend/views/flight/_search-form-flight') ?>
        </div>
    <?php endif;?>

</div>

<div id="loader-flight-search">
    <div class="loader-main">
        <div></div>
    </div>
    <!--<img src="/images/loaders/loader.gif" alt="load...">-->
</div>
<div id="selected-item"class="recomendation-bl center"></div>
<div class="recomendation_filter"></div>
<div id="search-result"></div>
<div id="back-result" style="display: none;"></div>
<div id="book-form"></div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */

$this->title = 'Логин';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login qway-wrap">

    <?= $this->render('_login-form', ['model' => $model]) ?>

</div>

frontend/views/site/next-trip.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use modules\flight\frontend\models\ElectronicTickets;
use yii\bootstrap\Modal;

$this->title = 'Следуюшая поездка';
$this->params['breadcrumbs'][] = $this->title;

\modules\flight\frontend\assets\ProfileAsset::register($this);
?>
<div class="site-next-trip qway-wrap">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php

    $allTicketsUser = ElectronicTickets::find()->where(['user_id' => Yii::$app->user->identity->id])->all();
    /* @var $ticket ElectronicTickets */
    foreach ($allTicketsUser as $ticket) : ?>
        <?php
        $currentTime = time();
        $ticketDepartureDate = explode(';', $ticket->departure_datetime)[0];
        $ticketDepartureTimeArray = explode('T', $ticketDepartureDate);
        $ticketDepartureTime = strtotime($ticketDepartureTimeArray[0] . ' ' . $ticketDepartureTimeArray[1]);


        if ($currentTime < $ticketDepartureTime) : ?>
            <div>
                номер билета: <?= $ticket->ticket_number ?><br>

                TotalFare: <?= $ticket->total_fare ?><br>
                <?php
                if ($ticket->exchange === ElectronicTickets::PENALTY_READY) {
                    echo Html::button('Условия обмена', [
                        'class' => 'penalty-condition',
                        'data' => [
                            'action' => 'exchange',
                            'key' => $ticket->id,
                            'before' => $ticket->exchange_before_departure,
                            'after' => $ticket->exchange_after_departure,
                        ]
                    ]);
                }

                if ($ticket->refunds === ElectronicTickets::PENALTY_READY) {
                    echo Html::button('Условия возврата', [
                        'class' => 'penalty-condition',
                        'data' => [
                            'key' => $ticket->id,
                            'action' => 'refunds',
                            'before' => $ticket->refunds_before_departure,
                            'after' => $ticket->refunds_after_departure,
                        ]
                    ]);
                }
                ?>
            </div>
        <?php endif; ?>
        <hr>
    <?php endforeach; ?>

</div>

<?php
Modal::begin([
    'header' => '<h3>Штрафы</h3>',
    'id' => 'penalty-modal-client',
    /*'options' => [
        'class' => 'book-modal'
    ]*/
]);
?>
<div id="penalty-content">
    <div class="before">
        До первого вылета: <span></span>
    </div>
    <div class="after">
        После первого вылета: <span></span>
    </div>

    <button type="button" class="penalty-confirm"></button>
</div>
<?php
Modal::end();